# 1. Origin Access Control (OAC)
# Note: Using the exact name generated by AWS to avoid recreation attempts
resource "aws_cloudfront_origin_access_control" "current" {
  name                              = var.oac_name
  description                       = "Created by CloudFront"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

# 2. CloudFront Distribution
resource "aws_cloudfront_distribution" "frontend" {
  enabled             = true
  is_ipv6_enabled     = true
  comment             = var.distribution_comment
  default_root_object = var.default_root_object
  price_class         = var.price_class
  http_version        = "http2"

  aliases = var.domain_aliases

  # Origin Configuration (S3)
  origin {
    domain_name = aws_s3_bucket.frontend.bucket_regional_domain_name
    # Exact Origin ID from state
    origin_id                = var.origin_id
    origin_access_control_id = aws_cloudfront_origin_access_control.current.id

    connection_attempts = 3
    connection_timeout  = 10
  }

  # Default cache behavior
  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = var.origin_id

    # Using AWS Cache Policy (CachingOptimized) as per state
    cache_policy_id = var.cache_policy_id

    viewer_protocol_policy = "redirect-to-https"
    compress               = true
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
      locations        = []
    }
  }

  viewer_certificate {
    acm_certificate_arn      = var.acm_certificate_arn
    ssl_support_method       = "sni-only"
    minimum_protocol_version = var.minimum_protocol_version
  }

  # Tags
  tags = {
    Name = var.cloudfront_tag_name
  }
}