variable "domain_name" {
  description = "Primary domain name for the hosted zone"
  type        = string
}

variable "zone_comment" {
  description = "Comment for the hosted zone"
  type        = string
}

variable "cloudfront_domain_name" {
  description = "CloudFront distribution domain name (e.g., dxxxx.cloudfront.net)"
  type        = string
}

variable "evaluate_target_health" {
  description = "Whether Route 53 should evaluate the health of the target (typically false for CloudFront)"
  type        = bool
  default     = false
}

variable "acm_validation_prefix" {
  description = "Random prefix generated by AWS ACM for the record name (e.g., _e6d8...)"
  type        = string
}

variable "acm_validation_target" {
  description = "Target value generated by AWS ACM (e.g., _2ac3....acm-validations.aws.)"
  type        = string
}

variable "www_subdomain" {
  description = "WWW subdomain for the website"
  type        = string
  default     = "www"
}

variable "create_www_record" {
  description = "Whether to create the WWW record"
  type        = bool
  default     = true
}